server:
  port: 8081
  servlet:
    contextPath: /market

spring:
  application:
    name: market-app
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    url: "jdbc:postgresql://localhost:5432/market_app"
  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug

